// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEHsyOvucNt-MpdJn8vTurWwnVIQc8OAU',
    appId: '1:541373362556:web:5926fdac33d97491a3b4f9',
    messagingSenderId: '541373362556',
    projectId: 'homechat-335ba',
    authDomain: 'homechat-335ba.firebaseapp.com',
    storageBucket: 'homechat-335ba.appspot.com',
    measurementId: 'G-2YHHJ7DGGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNiXM6rUC8-R6VOr5XW2vUppgqkzhu7LI',
    appId: '1:541373362556:android:e3e375c94b328fdea3b4f9',
    messagingSenderId: '541373362556',
    projectId: 'homechat-335ba',
    storageBucket: 'homechat-335ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAud5BzEmyiZDT12Vs2WVnG-7FcNgsqEpo',
    appId: '1:541373362556:ios:637f4640e993cec5a3b4f9',
    messagingSenderId: '541373362556',
    projectId: 'homechat-335ba',
    storageBucket: 'homechat-335ba.appspot.com',
    iosBundleId: 'com.example.homechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAud5BzEmyiZDT12Vs2WVnG-7FcNgsqEpo',
    appId: '1:541373362556:ios:189672f0c843a1e7a3b4f9',
    messagingSenderId: '541373362556',
    projectId: 'homechat-335ba',
    storageBucket: 'homechat-335ba.appspot.com',
    iosBundleId: 'com.example.homechat.RunnerTests',
  );
}
